//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krasnoyarsk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest_Services
    {
        public int id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public int quantity { get; set; }
        public string status { get; set; }
    
        public virtual Reservations Reservations { get; set; }
        public virtual Services Services { get; set; }
    }
}
