//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krasnoyarsk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Access
    {
        public int id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public string access_card_code { get; set; }
        public string status { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
